# Generated by Django 4.2.6 on 2023-10-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание курса')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_apptraining/', verbose_name='Превью')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата последнего изменения')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курсы',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.CharField(blank=True, max_length=250, null=True, verbose_name='Описание урока')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image_apptraining/', verbose_name='Превью')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('last_modified_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата последнего изменения')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptraining.course', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ('name',),
            },
        ),
    ]
